version: '3.8'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pack_upload_manager
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pack_upload_manager
      NODE_ENV: development
    ports:
      - '5173:5173' # SvelteKit default
    volumes:
      - src:/app/src
      - ./prisma:/app/prisma
      - ./static:/app/static
      - node_modules:/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ['/app/entrypoint.sh']

volumes:
  db_data:
  node_modules:
  src:
