version: '3.8'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pack_upload_manager
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pack_upload_manager
      NODE_ENV: development
    ports:
      - '5173:5173' # SvelteKit default
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - node_modules:/app/node_modules
    depends_on:
      - db
    entrypoint: ['/app/entrypoint.sh']

volumes:
  db_data:
  node_modules:
